;******************************************************************************
;									      *
; Filename: Robokeeper_V.3_Main.asm					      *
; Date: September 23 2025						      *
; File Version: 3							      *
; Author: Rahiel Rodriguez						      *
; Company: Idaho State University					      *
; Description: Firmware to control a robotic goalkeeper using a PIC16F1788.   *
;									      *
;******************************************************************************
;******************************************************************************
;									      *
; Revision History:							      *
;1:									      *
;								    	      *
;									      *
;									      *
;									      *
;									      *
;									      *
;									      *
;									      *
;******************************************************************************

; PIC16F1788 Configuration Bit Settings

; Assembly source line config statements

#include "p16f1788.inc"
#INCLUDE "Robokeeper_V.3_Setup.inc"
#INCLUDE "Timing_Cycles_1.inc"
;#INCLUDE "Testing_Timing.inc"
    
; CONFIG1
; __config 0x3FDF
; CONFIG1
; __config 0x39C4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON

 
	ORG	H'000'
	GOTO	SETUP
	
	ORG	H'004'
	GOTO	INTERRUPT
	
SETUP
	CALL	INITIALIZE
	GOTO	MAIN
;	GOTO	ENABLE_ROUTINE
;---------------------------------ISR------------------------------------------
INTERRUPT
	MOVWF	W_SAVE
	MOVFW	STATUS
	MOVWF	STATUS_SAVE
	CLRF	STATUS
	BANKSEL	PIR1
	BTFSC	PIR1,5
	GOTO	RECEIVE_ISR
;	BANKSEL	INTCON
;	BTFSC	INTCON,0
;	GOTO	SENSOR_SELECT
;	GOTO	FLEX_ISR
;	BTFSC	IOCCF,1
;	GOTO	MOTION_SENS_ISR
	GOTO	END_ISR

END_ISR
	BANKSEL	PIR1
	CLRF	PIR1
;	BANKSEL	PIR1
;	CLRF	PIR1
	BANKSEL	STATUS
	MOVFW	STATUS_SAVE
	MOVWF	STATUS
	MOVFW	W_SAVE
	RETFIE

RECEIVE_ISR
	BANKSEL	RCREG
	MOVFW	RCREG
	BANKSEL RECEIVE_SAVE
	MOVWF	RECEIVE_SAVE
	MOVFW	RECEIVE_SAVE
	MOVWF	POSITION_DATA
	BANKSEL	MOTION_FLAGS_REG
	BSF	MOTION_FLAGS_REG,0
	GOTO	END_ISR
	
;-----------------------------------MAIN---------------------------------------	
DIRECTION_DELAY		;Delay loop to make a correct direction change
	MOVLW	0X0F
	BANKSEL	COUNTER2
	MOVWF	COUNTER2

DIR_LOOP2
	MOVLW	0X54
	MOVWF	COUNTER1
DIR_LOOP1
	DECFSZ	COUNTER1
	GOTO	DIR_LOOP1
	DECFSZ	COUNTER2
	GOTO	DIR_LOOP2
	RETURN
	
OVERFLOW_CHECK_ROUTINE	
;	BANKSEL	IOCCF
;	MOVFW	IOCCF
;	MOVWF	SENSORS_F_REG
	BANKSEL	PORTA
	BTFSS	STATUS,0
	GOTO	SPEED_CHECK_ROUTINE
;	BSF	PORTB,0
;	CLRF	MOTION_FLAGS_REG
	MOVLW	H'01'
	MOVWF	SPEED_REG1
	MOVLW	H'01'
	MOVWF	SPEED_REG2
	CLRF	MOTION_FLAGS_REG
;	GOTO	POSITION_VERIFICATION
;	GOTO	SIGNAL_ROUTINE
;	BCF	PORTB,0
	GOTO	SENSOR_SELECT
	
SPEED_CHECK_ROUTINE
	BANKSEL	PORTA
;	BSF	PORTB,0
	CALL	SPEED_CHECK
	GOTO	CALIBRATION_SIGNAL_ROUTINE
	
CALIBRATION_SIGNAL_ROUTINE
	BANKSEL	PORTA
	BSF	PORTA,0
	CALL	CALIBRATION_DELAY
	BCF	PORTA,0
	CALL	CALIBRATION_DELAY
	DECFSZ	POSITION_COUNTER
	GOTO	CALIBRATION_SIGNAL_ROUTINE
	MOVLW	H'18'
	MOVWF	POSITION_COUNTER
;	GOTO	POSITION_VERIFICATION
	BTFSC	SPEED_REG2,5
	GOTO	SIGNAL_ROUTINE
	BTFSC	MOTION_FLAGS_REG,1
	GOTO	FORWARD_SHIFT1
	BTFSC	MOTION_FLAGS_REG,2
	GOTO	REVERSE_SHIFT1
	BTFSC	MOTION_FLAGS_REG,3
	GOTO	FORWARD_SHIFT2
	BTFSC	MOTION_FLAGS_REG,4
	GOTO	REVERSE_SHIFT2
	GOTO	OVERFLOW_CHECK_ROUTINE

FORWARD_SHIFT1
	LSLF	SPEED_REG1,1
	MOVFW	SPEED_REG1
;	MOVWF	PORTB
	GOTO	OVERFLOW_CHECK_ROUTINE
REVERSE_SHIFT1
	LSRF	SPEED_REG1,1
	MOVFW	SPEED_REG1
;	MOVWF	PORTB
	GOTO	OVERFLOW_CHECK_ROUTINE
FORWARD_SHIFT2
;	BSF	PORTB,0
	LSLF	SPEED_REG2,1
	MOVFW	SPEED_REG2
;	MOVWF	PORTB
	GOTO	OVERFLOW_CHECK_ROUTINE
REVERSE_SHIFT2
;	BCF	PORTB,0
	LSRF	SPEED_REG2,1
	MOVFW	SPEED_REG2
;	MOVWF	PORTB
	GOTO	OVERFLOW_CHECK_ROUTINE

SIGNAL_ROUTINE
;	BSF	PORTB,0
	BANKSEL	PORTA
	BSF	PORTA,0
	CALL	SIGNAL_DELAY
	BCF	PORTA,0
	CALL	SIGNAL_DELAY
	DECFSZ	CURRENT_STEPS
	GOTO	SIGNAL_ROUTINE
	MOVFW	STEPS_OBJ
	MOVWF	CURRENT_STEPS
	DECFSZ	STEP_MULT_COUNT
	GOTO	SIGNAL_ROUTINE
	MOVFW	STEPS_OBJ
	MOVWF	CURRENT_STEPS
	MOVLW	STEPS_MULTIPLIER
	MOVWF	STEP_MULT_COUNT
	DECFSZ	COMP_MULT_COUNT
	GOTO	SIGNAL_ROUTINE
	MOVFW	STEPS_OBJ
	MOVWF	CURRENT_STEPS
	MOVLW	STEPS_MULTIPLIER
	MOVWF	STEP_MULT_COUNT
	BSF	MOTION_FLAGS_REG,4
	BCF	MOTION_FLAGS_REG,3
	LSRF	SPEED_REG2,1
	GOTO	OVERFLOW_CHECK_ROUTINE
;	CLRF	MOTION_FLAGS_REG
;	GOTO	POSITION_VERIFICATION
	
SENSOR_SELECT
	BANKSEL	PORTC
	BTFSC	PORTC,0
	GOTO	FLEX_SENS_ROUTINE
	BTFSC	PORTC,1
	GOTO	MOTION_SENS_ROUTINE
	BSF	PORTB,2
	MOVLW	H'E8'
	MOVWF	TIMING_REG
	CALL	SENSOR_CHECK_DELAY
	DECFSZ	MISSED_T_REG
	GOTO	SENSOR_SELECT
	CLRF	PORTB
	MOVLW	H'FF'
	MOVWF	MISSED_T_REG
	MOVLW	H'30'
	BANKSEL	TXREG
	MOVWF	TXREG
	GOTO	POSITION_VERIFICATION
	
FLEX_SENS_ROUTINE
	BANKSEL	PORTB
	BCF	PORTB,2
	BSF	PORTB,0
	MOVLW	H'FF'
	MOVWF	MISSED_T_REG
	BCF	PORTB,2
	MOVLW	H'20'
	BANKSEL	TXREG
	MOVWF	TXREG
	GOTO	POSITION_VERIFICATION
	
MOTION_SENS_ROUTINE
	BANKSEL	PORTB
	BCF	PORTB,2
	BSF	PORTB,4
	MOVLW	H'FF'
	MOVWF	MISSED_T_REG
	BCF	PORTB,2
	MOVLW	H'28'
	BANKSEL	TXREG
	MOVWF	TXREG
	GOTO	POSITION_VERIFICATION
	
DIRECTION_CHANGE
	BANKSEL	PORTC
	CLRF	MOTION_FLAGS_REG
	BSF	MOTION_FLAGS_REG,1
	MOVLW	H'80'		    ;Direction Bit Check
	SUBWF	POSITION_DATA,0
	MOVWF	SUB_RESULT_SAVE	    ;Compares Direction Bit to see if is set or cleared
	BTFSS	STATUS,0
	GOTO	RIGHT_DIRECTION	    ;Negative Result
	GOTO	LEFT_DIRECTION	    ;Positive Result
	
RIGHT_DIRECTION
	BANKSEL	PORTA
	BCF	PORTA, 1
	MOVFW	POSITION_DATA	    ;Direction Bit was cleared, loads original data
	MOVWF	STEPS_OBJ
	CALL	DIRECTION_DELAY	    ;Adds delay needed for correct direction change
;	MOVFW	STEPS_OBJ
;	MOVWF	PORTB
	MOVFW	STEPS_OBJ
	MOVWF	CURRENT_STEPS
	CALL	COMPENSATION_ROUTINE
	BCF	STATUS,0
;	BANKSEL	PORTA
;	BSF	PORTB,0
	GOTO	OVERFLOW_CHECK_ROUTINE  ;Calls ramp up frequency routine
;	GOTO	SIGNAL_ROUTINE
;	GOTO	SPEED_CHECK_ROUTINE
	
LEFT_DIRECTION
	BANKSEL	PORTA
	BSF	PORTA, 1
	MOVFW	SUB_RESULT_SAVE	    ;Direction Bit was set, loads subtraction result to save steps info
	MOVWF	STEPS_OBJ
	CALL	DIRECTION_DELAY	    ;Adds delay needed for correct direction change
;	MOVFW	STEPS_OBJ
;	MOVWF	PORTB
	MOVFW	STEPS_OBJ
	MOVWF	CURRENT_STEPS
	CALL	COMPENSATION_ROUTINE
;	BANKSEL	PORTA
;	BSF	PORTB,0
	BCF	STATUS,0
	GOTO	OVERFLOW_CHECK_ROUTINE  ;Calls ramp up frequency routine
;	GOTO	SIGNAL_ROUTINE
;	GOTO	SPEED_CHECK_ROUTINE
	
HOMING_SEQUENCE
	BANKSEL	PORTA
	BSF	PORTA,0	;Sets RA0 for a certain amount of time
	CALL	HOME_PULSE_DELAY
	BCF	PORTA,0	;clears RA0 for a certain amount of time
	CALL	HOME_PULSE_DELAY	;So it can be around %50DC
	CALL	HOME_DIRECTION_CHANGE
	CALL	DIRECTION_DELAY
	BTFSS	PORTA, 2
	GOTO	HOMING_SEQUENCE
	BANKSEL	PORTC
	CLRF	MOTION_FLAGS_REG
	MOVLW	H'BD'
	BANKSEL	TXREG
	MOVWF	TXREG
	GOTO	POSITION_VERIFICATION
	
HOME_DIRECTION_CHANGE	    ;Checks if any Direction Sensor is activated
	BANKSEL	PORTA
	BCF	PORTA,0
	BTFSC	PORTA,3    ;If RA3 is set, go to the RIGHT
	BCF	PORTA,1
	BTFSC	PORTA,4    ;If RA4 is set, go to the LEFT
	BSF	PORTA,1
	RETURN
	
ENABLE_DELAY		    ;Enable Timing Loop
	BANKSEL	COUNTER3
	MOVWF	COUNTER3
ENABLE_LOOP3
	MOVLW	0X80
	MOVWF	COUNTER2	
ENABLE_LOOP2
	MOVLW	0X80
	MOVWF	COUNTER1
ENABLE_LOOP1
	DECFSZ	COUNTER1
	GOTO	ENABLE_LOOP1
	DECFSZ	COUNTER2
	GOTO	ENABLE_LOOP2
	DECFSZ	COUNTER3
	GOTO	ENABLE_LOOP3
	RETURN
	
ENABLE_ROUTINE
	BANKSEL	PORTC
;	BSF	PORTC, 3	;Set Enable Pin to de-activate the Steper Driver
	MOVLW	0X28
	CALL	ENABLE_DELAY	;Calls the minimum delay needed to allow Driver to Stop
;	BCF	PORTC, 3	;Clears Enable Pin to activate the Steper Driver
	MOVLW	0X28
	CALL	ENABLE_DELAY	;Calls the minimum delay needed to allow Driver to Work
	
;	MOVFW	SPEED_REG
;	MOVWF	PORTB
	
	MOVLW	STEPS_MULTIPLIER
	MOVWF	STEP_MULT_COUNT
;	BANKSEL	PORTA
;	BSF	PORTB,0
	GOTO	MAIN
	
MAIN
	BANKSEL	PORTC
	MOVLW	STEPS_MULTIPLIER
	MOVWF	STEP_MULT_COUNT
	GOTO	POSITION_VERIFICATION
	
POSITION_VERIFICATION
;------NO TASK SEQUENCE------	
;	MOVLW	H'DD'
;	BANKSEL	TXREG
;	MOVWF	TXREG
;	MOVLW	0X28
;	CALL	ENABLE_DELAY
	BANKSEL	PORTA
	BTFSS	MOTION_FLAGS_REG,0 ;Checks if all CPU Information was received
	GOTO	POSITION_VERIFICATION ;If not, do not do anything until all information was received
	MOVFW	POSITION_DATA
	SUBLW	H'BD'
	BTFSC	STATUS,2
	GOTO	HOMING_SEQUENCE
	GOTO	DIRECTION_CHANGE
	BANKSEL	MOTION_FLAGS_REG
	CLRF	MOTION_FLAGS_REG
	GOTO	POSITION_VERIFICATION
	END